---
- name: Pull backend Docker image
  community.docker.docker_image:
    name: "{{ backend_image }}"
    source: pull
    state: present

- name: Run backend container
  community.docker.docker_container:
    name: nyange-yolo-backend
    image: "{{ backend_image }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network }}"
    env:
      MONGODB_URI: "mongodb://app-mongo:27017/{{ db_name }}"
    ports:
      - "{{ backend_port }}:{{ backend_port }}"
  tags: [backend]